#!/bin/bash 

host="<HOST_NAME>"
port=<PORT_NUMBER>
username="<USERNAME>"
password="<PASSWORD>"

databases=(`psql -h $host -p $port -t -U $username -d sourceri -c "SELECT datname FROM pg_database WHERE datistemplate = 'false' and datname not like '%admin%'"`)

for d in "${databases[@]}"
do
echo $d
pg_dump -h $host -p $port -U $username -d $d > "${d}_suffix.sql"
pg_dumpall -h $host -p $port -U $username -d $d > "${d}_suffix.sql"
done
